# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbanking.proto\"R\n\x0c\x42\x61nkingReply\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05money\x18\x03 \x01(\x05\x12\x10\n\x08writeset\x18\x04 \x03(\x05\"D\n\x0e\x42\x61nkingRequest\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\r\n\x05money\x18\x02 \x01(\x05\x12\x10\n\x08writeset\x18\x03 \x03(\x05\x32h\n\x06\x42ranch\x12/\n\x0bMsgDelivery\x12\x0f.BankingRequest\x1a\r.BankingReply\"\x00\x12-\n\tMsgUpdate\x12\x0f.BankingRequest\x1a\r.BankingReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BANKINGREPLY']._serialized_start=17
  _globals['_BANKINGREPLY']._serialized_end=99
  _globals['_BANKINGREQUEST']._serialized_start=101
  _globals['_BANKINGREQUEST']._serialized_end=169
  _globals['_BRANCH']._serialized_start=171
  _globals['_BRANCH']._serialized_end=275
# @@protoc_insertion_point(module_scope)
